### ISSUE TITLE
New to Git hub need assistance.

### ISSUE THREAD

**Issue by sunglant** [id/zookeeper-el7-rpm#8]
Hello all, 

I am new to this entire process.  Can someone please let me know how to build an RPM for zookeeper-3.4.13?  I am not sure what to do where to pull the files from and then how to actually put it all together.  I am attempting to stand up confluent-kafka with zookeeper I have the rpm's for kafka but cannot find rpm's for zookeeper.

**Comment by rofr** [comment]
Download and extract this repo. Then edit the VERSION variable in the Makefile and then follow the instructions in the README.
